apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: prometheus-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: prometheus
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: prometheus
      maxAllowed:
        cpu: "4"
        memory: 28G
    # Due to CVE-2019-5736 runC is initially loaded into memory when the container starts.
    # After some time VPA recommends less memory (2,3Mb) than the size of runC binary (about 10Mb).
    # This results in an error when trying to start the container:
    # failed to write 2485760 to memory.limit_in_bytes in /sys/fs/cgroup/memory/kubepods/prometheus-config-reloader/memory.limit_in_bytes: device or resource busy
    # https://github.com/lxc/lxc/commit/6400238d08cdf1ca20d49bafb85f4e224348bf9d
    # https://github.com/helm/charts/issues/11447#issuecomment-464716379
    - containerName: prometheus-config-reloader
      mode: "Off"
    - containerName: '*'
      controlledValues: RequestsOnly
