networks:
  pods: 100.96.0.0/11
  services: 100.64.0.0/13
  nodes: 10.250.0.0/16
# global:
#   shootKubeVersion:
#     gitVersion: v1.6.4

images:
  prometheus: image-repository:image-tag
  vpn-seed: image-repository:image-tag
  blackbox-exporter: image-repository:image-tag

ingress:
  class: nginx
  hosts:
  - hostName: p.seed-1.example.com
    secretName: prometheus-tls
  # admin : admin base64 encoded
  authSecretName: auth-secret-name

kubernetesVersion: 1.25.4
secretNameClusterCA: ca
secretNameEtcdCA: ca-etcd
secretNameEtcdClientCert: etcd-client-tls

namespace:
  uid: 100c3bb5-48b9-4f88-96ef-48ed557d4212

podAnnotations: {}
replicas: 1
apiserverServiceIP: 100.10.10.10
port: 9090

additionalScrapeConfigs: ""
additionalRules: ""

allowedMetrics:
  alertManager:
  - alertmanager_config_hash
  - alertmanager_config_last_reload_successful
  - process_max_fds
  - process_open_fds
  cAdvisor:
  - container_cpu_cfs_periods_total
  - container_cpu_cfs_throttled_seconds_total
  - container_cpu_cfs_throttled_periods_total
  - container_cpu_usage_seconds_total
  - container_fs_inodes_total
  - container_fs_limit_bytes
  - container_fs_usage_bytes
  - container_last_seen
  - container_memory_working_set_bytes
  - container_network_receive_bytes_total
  - container_network_transmit_bytes_total
  cloudControllerManager:
  - rest_client_requests_total
  - process_max_fds
  - process_open_fds
  machineControllerManager:
  - mcm_workqueue_adds_total
  - mcm_workqueue_depth
  - mcm_workqueue_queue_duration_seconds_bucket
  - mcm_workqueue_queue_duration_seconds_sum
  - mcm_workqueue_queue_duration_seconds_count
  - mcm_workqueue_work_duration_seconds_bucket
  - mcm_workqueue_work_duration_seconds_sum
  - mcm_workqueue_work_duration_seconds_count
  - mcm_workqueue_unfinished_work_seconds
  - mcm_workqueue_longest_running_processor_seconds
  - mcm_workqueue_retries_total
  - mcm_cloud_api_requests_failed_total
  - mcm_cloud_api_requests_total
  - mcm_machine_controller_frozen
  - mcm_machine_deployment_failed_machines
  - mcm_machine_items_total
  - mcm_machine_set_failed_machines
  - mcm_machine_deployment_items_total
  - mcm_machine_set_items_total
  - mcm_scrape_failure_total
  - mcm_machine_current_status_phase
  - process_max_fds
  - process_open_fds
  prometheus:
  - process_max_fds
  - process_open_fds
  - process_resident_memory_bytes
  - process_virtual_memory_bytes
  - prometheus_config_last_reload_successful
  - prometheus_engine_query_duration_seconds
  - prometheus_rule_group_duration_seconds
  - prometheus_rule_group_iterations_missed_total
  - prometheus_rule_group_iterations_total
  - prometheus_tsdb_blocks_loaded
  - prometheus_tsdb_compactions_failed_total
  - prometheus_tsdb_compactions_total
  - prometheus_tsdb_compactions_triggered_total
  - prometheus_tsdb_head_active_appenders
  - prometheus_tsdb_head_chunks
  - prometheus_tsdb_head_gc_duration_seconds
  - prometheus_tsdb_head_gc_duration_seconds_count
  - prometheus_tsdb_head_samples_appended_total
  - prometheus_tsdb_head_series
  - prometheus_tsdb_lowest_timestamp
  - prometheus_tsdb_reloads_failures_total
  - prometheus_tsdb_reloads_total
  - prometheus_tsdb_storage_blocks_bytes
  - prometheus_tsdb_wal_corruptions_total
seed:
  apiserver: https://api.foo.bar
  region: antarctica-1
  provider: penguin

shoot:
  apiserver: https://api.foo.bar
  apiserverServerName: api.foo.bar
  provider: aws
  workerless: false

rules:
  optional:
    alertmanager:
      enabled: false

alerting:
  auth_type: {}
#     none:
#       url: foo.bar
#     basic:
#       url: foo.bar
#       username: admin
#       password: password
#     certificate:
#       url: foo.bar
#       ca.crt: ca
#       tls.crt: certificate
#       tls.key: key
#       insecure_skip_verify: false

ignoreAlerts: false

resources:
  requests:
    cpu: 200m
    memory: 360Mi

#remoteWrite:
#  url: remoteWriteUrl
#  queue_config: |
#     max_shards: 100
#     batch_send_deadline: 20s
#     min_backoff: 500ms
#     max_backoff: 60s
#  basic_auth:
#    username: user
#    password: password
#  keep:
#  - metric1
#  - metric2
#  - metric3
#  - metric4

#externalLabels:
#  env: test
